name: tutorial_flutter_json_parsing
description: A new Flutter application.


version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  json_annotation: ^2.0.0

  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: ^1.2.8
  json_serializable: ^2.0.2

flutter:

  uses-material-design: true
